### ISSUE TITLE
[epic] Data Warehouse Changes

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/aggregator#25]
- [x] RedShift changes - see [slide 12](https://docs.google.com/presentation/d/14-tJ3Ca0qstmgwLENQh5jflChB4MxZoUkA96fFoqGbU/edit#slide=id.g19d87b7b2f_1_56) #27
  - [x] remove tables we don't need etc
  - [x] aggregate at day level not week level (but see https://github.com/cybergreen-net/pm/issues/75)
  - [x] add amplification factor
- [x] RDS Changes #28
  - [x] name tables with our new naming convention
  - [x] changes in fact table
  - [x] load data to fact table - maybe use datapackage libraries / tabulator (see http://frictionlessdata.io/guides/using-data-packages-in-python/#loading-into-an-sql-database)
  - [x] changes in dimensions - load auto from new ref data (can we datapackage.json to auto create the tables using datapackage py library)
  - [x] create the cubes

**Comment by rgrp** [comment]
@zelima made a couple of comments on the description. Not sure what the measures stuff is ...

Also think of stuff like:

- [tbd] New reference data integration
- Amplification factor included
- ...

**Comment by zelima** [comment]
All of this is already done, including reference data integration and amplification factor
