### ISSUE TITLE
Code exits with error if there is new asn/country in scanned data

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/aggregator#47]
If there is new asn/or country in new scanned data Loader script exits with error, while creating constraints.

```
ERROR:  insert or update on table "table_xxx" violates foreign key constraint "forign_key_name"
DETAIL:  Key (asn)=(yyyyy) is not present in table "table_yyyy".
```

### Tasks

- [ ] create functions that run queries to detect difference between fact table and dimension
- [ ] insert difference into dimension table under "unknown" name
- [ ] log the new entries inserted into dimension table

**Comment by zelima** [comment]
FIXED after load script checks the difference between dimension and fact tables and inserts difference in dimensions under `unknown` name
